### ISSUE TITLE
[Feature Request] Show/hide slices in Team Library instances 

### ISSUE THREAD

**Issue by moxamax** [bahadrix/figma-toggleslices#1]
This plugin is a life-saver to fill the missing feature of Figma. It works perfectly hiding nested slices in local pages, but not works for instances from global Team Library. Can I request to add the feature of show/hide slices in Team Library instances? Thank you.

**Comment by bahadrix** [comment]
Sorry for the latency, I've just fixed that and sent to Figma to publish. If you don't want to wait you can add plugin manually.

**Comment by bahadrix** [comment]
Fixed and pulished
